Add instruction and conversational data support
togethercomputer/together-python pull request #211
Opened 2024-11-04 15:44 UTC by artek0chumak

Issue #ENG-10912

Add support for instruction and conversational training data support for FT jobs.
The support goes in two ways:
- File checks to make sure the data is formatted correctly
- Add `train_on_inputs` flag to train on completion/assistance phrases

2024-11-05 09:02 UTC, mryab requested changes

2024-11-05 09:02 UTC, mryab commented on tests/unit/test_files_checks.py
> +def test_check_jsonl_valid_conversational_multiple_turns(tmp_path: Path):
What's the difference between this test and `test_check_jsonl_valid_conversational_single_turn`? Both of them seem to have 2 conversations with 2 turns each

2024-11-05 09:02 UTC, mryab commented on tests/unit/test_files_checks.py
> +    print(report)
Same here

2024-11-07 12:29 UTC, artek0chumak commented on src/together/cli/api/finetune.py
> +            **training_args,
That was actually a bug because only `training_args` is changed in default values logic.

2024-11-07 14:43 UTC, artek0chumak commented on src/together/cli/api/utils.py
> +                    value=value, boolean_type=self.name
Changed

2024-11-07 14:43 UTC, artek0chumak commented on src/together/cli/api/finetune.py
> +    help="Whether to mask the inputs in conversational data",
Rewrote

2024-11-07 14:44 UTC, artek0chumak commented on src/together/constants.py
> +REQUIRED_COLUMNS_CONVERSATION = ["role", "content"]
I renamed to `REQUIRED_COLUMNS_MESSAGE` instead. I think this is what you meant

2024-11-07 14:45 UTC, artek0chumak commented on src/together/utils/files.py
> +                            raise KeyError
Created a new excepion for this

2024-11-07 14:45 UTC, artek0chumak commented on src/together/utils/files.py
> +                        "Error parsing file. Could not detect a possible format for the line with the columns:\n"
Added

2024-11-07 14:45 UTC, artek0chumak commented on src/together/utils/files.py
> +                    if column not in json_line.keys():
No need, removed

2024-11-07 14:45 UTC, artek0chumak commented on src/together/utils/files.py
> +                if dataset_format is None:
Refactered, thank you!

2024-11-07 14:46 UTC, artek0chumak commented on src/together/utils/files.py
> +                        for turn in json_line[message_column]:
swapped

2024-11-07 14:46 UTC, artek0chumak commented on tests/unit/test_files_checks.py
> +    assert report["min_samples"]
Done

2024-11-08 14:49 UTC, mryab commented on src/together/cli/api/finetune.py
> +    help="Whether to mask the user messages in conversational data or prompts in instruction data",
Nit: might be good to explain what happens in the default case and how `auto` is handled

2024-11-08 14:49 UTC, mryab commented on src/together/resources/finetune.py
> +            train_on_inputs (bool, optional): Whether to mask the user messages in conversational data or prompts in instruction data.
bool or "auto"

2024-11-08 14:49 UTC, mryab commented on src/together/resources/finetune.py
> +                Defaults to "auto".
What does "auto" correspond to?

2024-11-08 14:49 UTC, mryab commented on src/together/resources/finetune.py
> +            train_on_inputs (bool, optional): Whether to mask the inputs in conversational data. Defaults to "auto".
Looks like this docstring is outdated

2024-11-08 14:49 UTC, mryab commented on src/together/utils/files.py
> +class InvalidFileFormatError(Exception):
Maybe inherit from a less generic class, like ValueError?

2024-11-08 14:49 UTC, mryab commented on src/together/utils/files.py
> +        self.field = field
I guess it's not a field but rather something like `error_type` or `error_source`

2024-11-08 14:49 UTC, mryab commented on tests/unit/test_files_checks.py
> +        f.write("\n".join([json.dumps(item) for item in content]))
```suggestion
        f.write("\n".join(json.dumps(item) for item in content))
```

2024-11-08 14:49 UTC, mryab commented on tests/unit/test_files_checks.py
> +    assert report["min_samples"] >= MIN_SAMPLES
min_samples is a boolean, are you sure we should compare it with the integer?

2024-11-08 14:49 UTC, mryab commented on tests/unit/test_files_checks.py
> +        f.write("\n".join([json.dumps(item) for item in content]))
```suggestion
        f.write("\n".join(json.dumps(item) for item in content))
```

2024-11-08 14:49 UTC, mryab commented on tests/unit/test_files_checks.py
> +        f.write("\n".join([json.dumps(item) for item in content]))
Same here and onwards

2024-11-08 14:49 UTC, mryab commented on src/together/utils/files.py
> +                                    message=f"Field '{column}' is missing for a turn `{turn}` on line {idx + 1} "
```suggestion
                                    message=f"Field `{column}` is missing for a turn `{turn}` on line {idx + 1} "
```

2024-11-08 14:49 UTC, mryab commented on src/together/utils/files.py
> +                                message=f"Found invalid role '{role}' in the messages on the line {idx + 1}. "
```suggestion
                                message=f"Found invalid role `{role}` in the messages on the line {idx + 1}. "
```

2024-11-08 14:49 UTC, mryab commented on src/together/utils/files.py
> +                                "'user' and 'assistant' roles must alternate user/assistant/user/assistant/...",
```suggestion
                                "`user` and `assistant` roles must alternate user/assistant/user/assistant/...",
```

2024-11-12 10:52 UTC, mryab commented on src/together/cli/api/finetune.py
> +    help="Whether to mask the user messages in conversational data or prompts in instruction data",
Up (you can just put `"auto" will automatically determine whether to mask the inputs based on the data format.` here)

2024-11-12 10:52 UTC, mryab commented on src/together/resources/finetune.py
> +                fields will mask the inputs by default.
```suggestion
                "auto" will automatically determine whether to mask the inputs based on the data format.
                For datasets with the "text" field (general format), inputs will not be masked.
                For datasets with "messages" (conversational format) or "prompt" and "completion" (instruction format)
                fields, inputs will be masked.
```

2024-11-12 10:52 UTC, mryab commented on src/together/resources/finetune.py
> +            train_on_inputs (bool or "auto"): Whether to mask the user messages in conversational data or prompts in instruction data.
Needs to be updated

2024-11-12 10:52 UTC, mryab commented on src/together/utils/files.py
> +                    previous_role = ""
```suggestion
                    previous_role = None
```

2024-11-12 10:52 UTC, mryab commented on src/together/utils/files.py
> +                    ][0]
Nit: this is dangerous, we implicitly assume that the first item in the list is the message column name

2024-11-13 15:20 UTC, zainhas commented
When I pass in `train_on_inputs="true" `or `train_on_inputs="false"` it should give me an error however it submits and completes the job - this is probably because "true", "false" are all truthy?

We should just be opinionated on what we accept as values for train_on_inputs and then error out for anything else and have detailed documentation.

Should we change the fact that users can pass in `train_on_inputs=None` and this will default to functionality like `train_on_inputs="auto"` since its not obvious  that None should be == "auto" functionality.

2024-11-13 16:19 UTC, zainhas commented
Reviewed new changes and lgtm👍

2024-11-13 16:35 UTC, zainhas approved these changes

2024-11-13 16:49 UTC, mryab commented on src/together/cli/api/finetune.py
> +            "LoRA rank default has been changed from 8 to 64 as the maximum available for each model."
Does this mean that every model supported by the API has 64 as the maximum possible rank? I think the current wording is confusing if this is not true

2024-11-13 16:49 UTC, mryab commented on src/together/resources/finetune.py
> +        raise ValueError("train_on_inputs cannot be None")
This is not allowed by the typing annotation itself, I believe we should not check for inputs that are not documented as permissible for the function

2024-11-13 16:49 UTC, mryab commented on src/together/resources/finetune.py
> +    train_on_inputs_bool = train_on_inputs if train_on_inputs != "auto" else None
It is not of boolean type if it gets mapped to None in one case

2024-11-13 16:49 UTC, mryab commented on tests/unit/test_files_checks.py
> +                {"role": "user", "content": "Who won the game last night?"},
Can we add a `system` message at the beginning of this conversation to ensure that these three roles are handled properly?

2024-11-14 17:03 UTC, artek0chumak commented on src/together/types/finetune.py
> +    train_on_inputs: StrictBool | Literal["auto"] | None = "auto"
Yup, it's for retrieve or any other command that can see an old data

2024-11-14 18:14 UTC, merged